### PR TITLE
feat: change theme toggler

### LINKED ISSUE #1534: [Feature]: add theme selector to the burger menu
### Description

add theme selector in the burger menu

image

### Explanation

like vercel does

### PR DESCRIPTION
**Pull request by aakash19here**
Closes #1534

## How Has This Been Tested?
Manually

## Screenshots/Video (if applicable):
Screenshot 2024-09-01 at 5 54 24 PM

### CODE REVIEW

**Comment by aakash19here** [comment]
Should I make a new PR for light theme issues ?

**Comment by bautistaaa** [comment]
> Should I make a new PR for light theme issues ?

yes please!

**Comment by bautistaaa** [comment]
i think you need to run `pnpm checks:fix` or fix the linting issues

**Comment by aakash19here** [comment]
> i think you need to run `pnpm checks:fix` or fix the linting issues

yeah sure , will do it in a while

**Comment by aakash19here** [comment]
Screenshot 2024-09-02 at 1 15 26 AM

Forgot to add theme toggler to mobile devices , this is how it looks

**Comment by bautistaaa** [comment]
this works great!

**Review by bautistaaa — APPROVED** [review]

**Comment by bautistaaa** [comment]
@aakash19here noticed on the challenge view its not toggling the editor theme

CleanShot 2024-09-02 at 09 38 32@2x

probably unrelated to your change but if you want to tackle it you can

**Comment by aakash19here** [comment]
> @aakash19here noticed on the challenge view its not toggling the editor theme
> 
> 
> 
> CleanShot 2024-09-02 at 09 38 32@2x

yeah , making a new PR to fix theme issues 🙌🏻

**Comment by bautistaaa** [comment]
> > @aakash19here noticed on the challenge view its not toggling the editor theme
> > CleanShot 2024-09-02 at 09 38 32@2x
> 
> yeah , making a new PR to fix theme issues 🙌🏻

https://github.com/typehero/typehero/issues/1541

**Pull request merged**
