### PR TITLE
fix: system theme issue

### LINKED ISSUE #1541: [Bug]: System theme selection not working correctly
### What happened?

when toggling system theme in macOS the editor theme and various other places are not the right color scheme.

https://github.com/user-attachments/assets/bb2a8b31-02c6-4761-9426-bb225949a9fe

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aakash19here**
Closes #1541

### CODE REVIEW

**Comment by aakash19here** [comment]
Lol , I was going to attach video for the preview

**Comment by bautistaaa** [comment]
its broken still on prod 😢

**Comment by aakash19here** [comment]
Working fine on my end

**Comment by aakash19here** [comment]
Uploading Screen Recording 2024-09-02 at 10.21.39 PM.mov…

**Comment by bautistaaa** [comment]
weird had a couple users confirm its not working

**Comment by aakash19here** [comment]
https://github.com/user-attachments/assets/51228538-b8ae-435d-a14d-5d119a6502b2

**Comment by bautistaaa** [comment]
you need to test it with the use case of the toggling the theme on their system vs through the UI on our site. it does in fact work via toggling via our site

CleanShot 2024-09-02 at 10 13 41

**Comment by aakash19here** [comment]
@bautistaaa @Hacksore 

For me it's still working fine even after doing the above thing

**Comment by Hacksore** [comment]
@aakash19here aint no way 💀

but here is my analysis of the problem. we have a bunch of calls like these which don't check the `systemTheme` property so it won't know if we should use a `light` or `dark` theme.

https://github.com/typehero/typehero/blob/d0d2ab00d1cceaa8ab8cec65e8b4ae7473955fcb/packages/ui/src/components/markdown.tsx#L57

https://github.com/typehero/typehero/blob/d0d2ab00d1cceaa8ab8cec65e8b4ae7473955fcb/apps/web/src/components/Navigation/theme-button.tsx#L35-L47

https://github.com/typehero/typehero/blob/d0d2ab00d1cceaa8ab8cec65e8b4ae7473955fcb/apps/web/src/components/rich-markdown-editor.tsx#L41-L56

https://github.com/typehero/typehero/blob/d0d2ab00d1cceaa8ab8cec65e8b4ae7473955fcb/apps/web/src/app/challenge/%5Bslug%5D/solutions/_components/solution-editor.tsx#L92-L95

https://github.com/typehero/typehero/blob/d0d2ab00d1cceaa8ab8cec65e8b4ae7473955fcb/apps/web/src/app/challenge/%5Bslug%5D/solutions/_components/edit-solution.tsx#L68-L71

https://github.com/typehero/typehero/blob/d0d2ab00d1cceaa8ab8cec65e8b4ae7473955fcb/packages/monaco/src/code-editor.tsx#L44

**Pull request merged**
