### PR TITLE
215 linkable comments

### PR DESCRIPTION
**Pull request by Rand0mLetters**
added a bit of linkability, still having some trouble highlighting comments + some of the code is really bad (I can't name variables for the life of me)

Here's a demo of the progress so far (as you can see, highlighting + scrolling still need to be implemented):

https://github.com/typehero/typehero/assets/108293579/bc6f2564-9df9-446c-9a7e-c761799a13c3

### CODE REVIEW

**Comment by Rand0mLetters** [comment]
uhhhh not sure what git just did, I'll figure that out + merge main tomorrow (if I have time) or tuesday

**Comment by Rand0mLetters** [comment]
haha I love git time to go to sleep

**Comment by Rand0mLetters** [comment]
here's a demo of how it works so far (fewer bugs than last commit, still some work to be done, like scrolling the comment into view)
https://github.com/typehero/typehero/assets/108293579/38f2a365-ad47-4af1-9ab0-b3d8d23f5bd3

**Comment by bautistaaa** [comment]
closing for https://github.com/typehero/typehero/pull/615

**Pull request closed without merging**
