### PR TITLE
618 - Added resizer to test panel

### LINKED ISSUE #618: [Feature]: Make collapsible test panel resizable
### Description

see https://leetcode.com/problems/split-linked-list-in-parts/?envType=daily-question&envId=2023-09-06 for an example

### Explanation

_No response_

### PR DESCRIPTION
**Pull request by michelettoluca**
## Description
Added resizer to the test panel

## Related Issue
closes #618 

## Screenshots/Video:
https://github.com/typehero/typehero/assets/74112450/c26ef154-d6b3-4ef4-85e4-7560b8397fdd

### CODE REVIEW

**Comment by bautistaaa** [comment]
appears to work pretty good. 

couple lines of feedback
- i think they should be able to go all the way up(not sure if thats possible)
- bottom bar needs a border top when not not expanded

**Comment by bautistaaa** [comment]
something odd is happening

- change settings to vim mode
- open test panel and resize to the top and youll see it reset the editor to standard bindings
- you can open up the local storage settings and see it get toggled. i suspect something is triggering the zustand store and its not finding the current settings and resets it to the default

**Comment by bautistaaa** [comment]
one last small thing: keep the border even when its expanded!

**Comment by michelettoluca** [comment]
It should be good now. I also added a listener on window resize because I didn't update the height accordingly, causing the drag resize to behave weirdly.

**Review by bautistaaa — APPROVED** [review]
great work! thanks for the PR

**Pull request merged**
