### PR TITLE
fix: Alert icon overlapping with the text on Firefox

### PR DESCRIPTION
**Pull request by heyanurag**
## Description
:has selector is not supported in FF yet. - See https://github.com/tailwindlabs/tailwindcss/discussions/10206#discussioncomment-6604020

This removes the :has selector from the Alert component and adds padding-left to AlertDescription instead.

## Motivation and Context
#677 

## How Has This Been Tested?
Tested on Chrome, Brave and FF browsers.

## Screenshots/Video (if applicable):
Before:
image

After:
image

After on Chrome (No difference):
image

### CODE REVIEW

**Review by bautistaaa — COMMENTED** [review]
there was an issue somewhere previously where someone added this but it broke other reolutions. can you make sure it works  as expected.

**Comment by bautistaaa** [comment]
did you validate all resolutions here?

**Comment by heyanurag** [comment]
> did you validate all resolutions here?

The Alert component was being used at one other place on the admin side.

Before:
image

After:
image


Here is a video for all resolutions. Looks good to me!

gif

**Comment by bautistaaa** [comment]
awesome, looks like you have some eslint errors. then we can merge. its probably the ordering of your classes

`pnpm checks:fix` might fix it

**Review by bautistaaa — APPROVED** [review]

**Review by QuiiBz — APPROVED** [review]
Nice fix!

**Pull request merged**
