### PR TITLE
feat(i18n): increase key + add fr translation

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

Adding more i18n key
Adding fr translation

## Related Issue

No related issue

## Motivation and Context

I18n allows as many people as possible to be included in their mother tongue

## How Has This Been Tested?

I just run `pnpm dev` and take a look on page if it's ok 👌🏻

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
@bautistaaa  👋

**Comment by bautistaaa** [comment]
@QuiiBz i dont speak french, are these translations right lol

**Comment by QuiiBz** [comment]
> @QuiiBz i dont speak french, are these translations right lol

Looks good to me

**Comment by bautistaaa** [comment]
we dont plan to actually support translations yet but doesnt hurt to have this for now

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
