### PR TITLE
Use markdown fix #553

### LINKED ISSUE #553: [Feature]: markdown in challenge cards
### Description

Instead of rendering backticks, use code bubbles/a monospaced font?
image

PS. I would like to help with this

### Explanation

It looks ugly right now

### PR DESCRIPTION
**Pull request by Hacksore**
dark:
image

light:
image

### CODE REVIEW

**Comment by Hacksore** [comment]
@PickleNik this needs line height fixed.

**Comment by bautistaaa** [comment]
das a lot of padding on those pills

**Comment by maxdemaio** [comment]
> [!NOTE]
> ## I can look into this 👍🏻

**Review by QuiiBz — APPROVED** [review]

**Comment by maxdemaio** [comment]
> [!NOTE]
> Pushed a commit to fix the clipping on the `/explore` page 👍🏻 

image

**Comment by bautistaaa** [comment]
> Note Pushed a commit to fix the clipping on the `/explore` page 👍🏻
> 
> image

if theres two code block on top of each other they are going to overlap it looks like. top and bottom padding seem big?

**Comment by Rand0mLetters** [comment]
could make the text inside the pills smaller (looks to be a lot bigger than the surrounding text just looking at the image)

also, what is the behaviour when the closing code tag (be it single or triple) is cropped out of the description?
could make the code pills inherit their font size from containing text?

**Comment by maxdemaio** [comment]
> if theres two code block on top of each other they are going to overlap it looks like. top and bottom padding seem big?

image

You're right. I can look into how to cook on this given @Rand0mLetters's comment 👍🏻

**Comment by maxdemaio** [comment]
Option 1 - make the padding a bit smaller, from 0.2 rem to 0.10 rem:
image

Option 2 - increase the line height on the code pills (I think this is best):
image

**Pull request merged**
