### PR TITLE
chore: remove waitlist table

### PR DESCRIPTION
**Pull request by bautistaaa**
## Description
We migrated to mailchimp so we no longer need the waitlist table or the unsubscribe form as this will be managed in settings later

### CODE REVIEW

**Comment by ayrock-dev** [comment]
to doc ur process here, do u run `prisma db push` on prod at some point after merging this with ur prod planetscale creds?

**Comment by bautistaaa** [comment]
> to doc ur process here, do u run `prisma db push` on prod at some point after merging this with ur prod planetscale creds?

ideally yes but since we have no data i just run pnpm refresh

**Review by jhechtf — APPROVED** [review]
LGTM

**Review by Hacksore — CHANGES_REQUESTED** [review]
wait but like, we would still have the waitlist button on the home page.

Remove it?

**Comment by bautistaaa** [comment]
> wait but like, we would still have the waitlist button on the home page.
> 
> Remove it?

everything looks the same we just use mail chimp. they have their own user mgmt so we don’t need unsubscribe

**Review by Hacksore — APPROVED** [review]

**Pull request merged**
