### PR TITLE
Update pnpm to latest v8

### PR DESCRIPTION
**Pull request by Hacksore**
Related but seems like it is working now?

vercel/turbo#7993

### CODE REVIEW

**Comment by bautistaaa** [comment]
why is this even a problem, fkkkk

**Comment by bautistaaa** [comment]
oh wtf? 

```
turbo: command not found
```

**Comment by Hacksore** [comment]
@bautistaaa Yeah idk maybe we can pair on this?

**Comment by bautistaaa** [comment]
> @bautistaaa Yeah idk maybe we can pair on this?

oh you totally removed the turbo install command lmao

CleanShot 2024-05-17 at 09 36 03

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
