### PR TITLE
Add sitemap

### PR DESCRIPTION
**Pull request by Hacksore**
add sitemap

task part of #705

### CODE REVIEW

**Comment by Hacksore** [comment]
tagging @QuiiBz as I think that this might have some implications on [next-international](https://github.com/QuiiBz/next-international).

**Comment by Hacksore** [comment]
considering just yeeting next-sitemap and just doing it manually like described here.

https://claritydev.net/blog/nextjs-dynamic-sitemap-pages-app-directory

**Comment by bautistaaa** [comment]
> considering just yeeting next-sitemap and just doing it manually like described here.
> 
> https://claritydev.net/blog/nextjs-dynamic-sitemap-pages-app-directory

yeah this seems to get the job done

**Comment by Hacksore** [comment]
@bautistaaa :shipit: it's good enough

**Pull request merged**
