### PR TITLE
fix: toast notification themes fix for success and destructive with hover effect

### PR DESCRIPTION
**Pull request by me-imfhd**
## Description
I have changed some peices of code by hit and trial method for what looks right,
removed text-black, making the text white,
and for hover:
i have removed hover:bg-secondary (which made hovering the toast action black) and changed to hover:bg-transparent/10 which just makes the hover identical with its background but a bit darker indicating we are hovering over it,
But this change did not affect the destructive notification beacause it had its own styles,
so fixed that, done the fix for both dark and light mode, the result is pretty much same for both dark and light mode.
## Related Issue
https://github.com/typehero/typehero/issues/1085
Closes #

## Screenshots/Video (if applicable):
Here are screenshot:
1) without hover : 
image
image

2) with hover:
image
image

### CODE REVIEW

**Comment by bautistaaa** [comment]
how does light mode look

**Comment by me-imfhd** [comment]
@bautistaaa 
success:
image
image

failure:
image
image

**Comment by bautistaaa** [comment]
i believe theres some formatting issues. can you run `pnpm checks:fix`

**Comment by me-imfhd** [comment]
> i believe theres some formatting issues. can you run `pnpm checks:fix`

Yess sir 👾

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
