### PR TITLE
525 resize left panel

### PR DESCRIPTION
**Pull request by Tylopilus**
competing solution to #525

uses framer-motion instead of huge ass useEffect

### CODE REVIEW

**Comment by bautistaaa** [comment]
this is intriguing. can you post a video of it on both mobile and desktop. our feature flags have everything turned off on preview. need to get that sorted

**Comment by Tylopilus** [comment]
@bautistaaa Here is the vid 
https://jmp.sh/rsr7ZbU4

pls help fixing lock conflict. how?

**Comment by Hacksore** [comment]
so I was looking #534 by @jproberson which imo is a better UX and follows more what VSCode does.

I'm inclined to take that approach more but will let others comment what they think. cc @bautistaaa

https://github.com/typehero/typehero/assets/996134/82ac72fc-aaf8-4b0c-bc03-0c1599c135a4

**Comment by PickleNik** [comment]
I do like the compactness and the smooth transition with framer, I hope there'll be a version of this after #534 is merged

**Pull request closed without merging**
