### PR TITLE
[docs]: update HeroDevs light/dark mode logo

### LINKED ISSUE #853: [docs]: herodevs-logo-not-legible-on-README-in-gh-lightmode
### What happened?

herodevs logo in README is not legible in GitHub light mode due to white text on white background.

light-mode-before

Issue is addressed in pr #852 

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by eduardoRoth**
## Description
Updates the HeroDevs logo in the README to use different pictures for light/dark mode.

## Related Issue

Closes #853

## Motivation and Context

I work at HeroDevs 😜

## How Has This Been Tested?

In my own fork

## Screenshots/Video (if applicable):
Light mode
image

Dark mode
image

### CODE REVIEW

**Comment by eduardoRoth** [comment]
My bad, I didn't see there was already a PR (#853) for this issue (as the issue was still opened and unassigned). Yet, my PR uses two images for light and dark mode (so same proportions and size); also, it removes the background of the image; so it kinda improves the HeroDevs logo 😅

**Comment by papadavis47** [comment]
Definitely the better solution to mine. Kudos 💯 

I'm just learning my way around here 😄

**Comment by bautistaaa** [comment]
shoot did i merge teh wrong one

can you undo @papadavis47 changes then @eduardoRoth if we want this one instead

**Comment by eduardoRoth** [comment]
@bautistaaa , mine didn't exist when @papadavis47 created his PR 😅

Actually, my change is over @papadavis47 one, as he changed the image to be a png instead of svg; and then I updated that to use two different images. But let me know if you prefer I revert his change.

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
