### PR TITLE
[Feat] :Move react-query logo to top right corner

### LINKED ISSUE #794: [Feature]: move tanstack query devtools logo somewhere not annoying on the screen
### Description

image

### Explanation

_No response_

### PR DESCRIPTION
**Pull request by vivekKumarSinghH**
## Description

Move react-query logo to top-right corner
## Related Issue

Closes #794

## Motivation and Context
Logo does not interfere with anything in top-right corner

## How Has This Been Tested?
Tested locally

## Screenshots/Video (if applicable):
image

### CODE REVIEW

**Comment by Hacksore** [comment]
Doesn't this get in the way of login now?

**Comment by vivekKumarSinghH** [comment]
> Doesn't this get in the way of login now?
noo
image

**Review by bautistaaa — APPROVED** [review]

**Comment by Hacksore** [comment]
FYI i think we still need a better location for this
image

**Comment by vivekKumarSinghH** [comment]
> FYI i think we still need a better location for this image

yes, but we can only choose from 4 corners

**Pull request merged**
