### PR TITLE
feat: load all replies when panel is expanded with load more behavior

### PR DESCRIPTION
**Pull request by oreoluwa-bs**
## Description

- Fetches all comments(replies) stores that in react query cache
- Added client side pagination for replies which is managed by `useInfiniteQuery`

## Related Issue

#711 

## Motivation and Context

#711

## How Has This Been Tested?

Manual clicking through the comments panel

## Screenshots/Video (if applicable):
https://github.com/typehero/typehero/assets/46888096/f93dbfa7-7627-40a7-9dfc-f53886d15e11

### CODE REVIEW

**Comment by bautistaaa** [comment]
looks great so far!

found a small bug

- if you create a new comment in the replies it does not appear(however the count updates). the new reply should append to the bottom

**Comment by oreoluwa-bs** [comment]
Thank you.
Had issues with invalidating the query. It took too long for the state to update so I opted for refetch interval instead.

**Comment by bautistaaa** [comment]
> Thank you. Had issues with invalidating the query. It took too long for the state to update so I opted for refetch interval instead.

this is broken for me

CleanShot 2023-09-26 at 21 51 36

**Comment by bautistaaa** [comment]
i was thinking you could probably just do optimistic updates or something

https://tanstack.com/query/v4/docs/react/guides/optimistic-updates

**Comment by oreoluwa-bs** [comment]
I thought about that also but it was also broken when you delete a comment

**Comment by bautistaaa** [comment]
the useeffect just spams the network tab now

ill take a stab at this as well

**Comment by oreoluwa-bs** [comment]
I realised it was because data was part of the dependency array

**Comment by oreoluwa-bs** [comment]
It's no longer spamming the network tab and changes are pagination is fully on the client

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
