### PR TITLE
Feat: Merged the profile menu and navigation into one mobile-friendly…

### LINKED ISSUE #1301: [Feature]: Need only one menu on Navbar
### What happened?

We currently have two menu(s) on the nav (for mobile) 
1. For Profile
Screenshot from 2023-12-10 14-11-03
3. For Nav Links
image

We need only one menu, having two menus can lead to confusion and is a waste of space.
 
Expected:
1. Put the three links (from profile menu) at the bottom on nav menu.
2. Remove the icons, keep the red color for logout.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PraveenShinde3**
feat(navbar): Combine profile and navigation menus for mobile view

## Related Issue
Closes #1301

## Motivation and Context
Addresses the issue of having only one menu on the navbar. Merged the profile menu and navigation menu to create a unified and mobile-friendly navigation experience.

## How Has This Been Tested?
Tested on various devices and browsers to ensure consistent behavior and responsiveness.

## Screenshots/Video (if applicable):
- Mobile View
    image
- Web View
    image

### CODE REVIEW

**Comment by zaCKoZAck0** [comment]
You forgot to add this I think https://github.com/typehero/typehero/blob/main/apps%2Fweb%2Fsrc%2Fcomponents%2FNavigation%2Findex.tsx#L144

**Comment by PraveenShinde3** [comment]
In the Issue #1301 it was mentioned that to add only 3 links from profile hence i have only added those 3 (Profile, Setting and Log out)

**Comment by zaCKoZAck0** [comment]
MB, Please Add.

**Comment by odicho** [comment]
Awesome work @PraveenShinde3!!

Do you think you'd be able to separate the original nav bar and the profile options somehow? e.g. Add a small header and separator.

I use vercel.com fairly often from mobile and I really like how they've added a tiny bit of separation between the sections. It makes it seamless and intuitive to navigate.
Screenshot_20231210_152709_Chrome

**Comment by PraveenShinde3** [comment]
@odicho Yes that is possible, will try to add that to

**Comment by PraveenShinde3** [comment]
@odicho @zaCKoZAck0  Please let me know is the UI looks ok ?

For Users
image


For Admin
image

**Comment by zaCKoZAck0** [comment]
> @odicho @zaCKoZAck0 Please let me know is the UI looks ok ?
> 
> For Users image
> 
> For Admin image

Works for me, great work.

**Comment by PraveenShinde3** [comment]
@zaCKoZAck0  Will create a New PR with the Above change is that fine? since this branch is having lot of issues,

**Comment by PraveenShinde3** [comment]
Closing this PR, since creating a new PR which will have the required changes.

**Pull request closed without merging**
