### PR TITLE
attempt to use bun

### PR DESCRIPTION
**Pull request by bautistaaa**
CleanShot 2023-09-09 at 00 44 23@2x

### CODE REVIEW

**Comment by bautistaaa** [comment]
relevant docs: https://bun.sh/docs/install/workspaces

**Comment by QuiiBz** [comment]
We'll probably want to update the `packageManager` field and remove `pnpm` from the root `package.json`

**Comment by bautistaaa** [comment]
whats the bun equivalent for 

```json
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": [
        "monaco-editor"
      ]
    },
    "patchedDependencies": {
      "next-auth@4.22.1": "patches/next-auth@4.22.1.patch",
      "@monaco-editor/react@4.5.1": "patches/@monaco-editor__react@4.5.1.patch",
      "monaco-vim@0.4.0": "patches/monaco-vim@0.4.0.patch",
      "@vercel/toolbar@0.1.1": "patches/@vercel__toolbar@0.1.1.patch"
    }
  },
```

**Comment by is-it-ayush** [comment]
@bautistaaa fixed the install stuff. (check the commit messages if you wanna dive into issues, i left link). in summary, turbo doesn't directly support bun yet. this workaround is to simulate a yarn lockfile for turbo to think yarn is being as a package manager.

use `bun install --yarn` & then `bun run dev`. it should work! ci is still broken tho

**Comment by jhechtf** [comment]
So I guess we're just abandoning Windows support T^T

**Comment by talhabalaj** [comment]
> whats the bun equivalent for
> 
> ```json
>   "pnpm": {
>     "peerDependencyRules": {
>       "ignoreMissing": [
>         "monaco-editor"
>       ]
>     },
>     "patchedDependencies": {
>       "next-auth@4.22.1": "patches/next-auth@4.22.1.patch",
>       "@monaco-editor/react@4.5.1": "patches/@monaco-editor__react@4.5.1.patch",
>       "monaco-vim@0.4.0": "patches/monaco-vim@0.4.0.patch",
>       "@vercel/toolbar@0.1.1": "patches/@vercel__toolbar@0.1.1.patch"
>     }
>   },
> ```

Bun doesn't have patching support yet, you might have to use `patch-package` which doesn't support Bun's binary lock file yet. but support is coming ds300/patch-package#490   

for peerDependencyRules, I can't find anything equivalent in Bun.

**Comment by Strengthless** [comment]
> Bun doesn't have patching support yet, you might have to use `patch-package` which doesn't support Bun's binary lock file yet. but support is coming [ds300/patch-package#490](https://github.com/ds300/patch-package/pull/490)

If they're going to simulate a yarn lockfile using `bun install --yarn`, as mentioned: 
> in summary, turbo doesn't directly support bun yet. this workaround is to simulate a yarn lockfile for turbo to think yarn is being as a package manager. use `bun install --yarn` & then `bun run dev`. it should work!

Then `patch-package` should work without a problem (for both creating and executing patches), see https://github.com/oven-sh/bun/issues/2336#issuecomment-1712458657 for more details.

**Pull request closed without merging**
