### PR TITLE
refresh inlay hints on code edits

### LINKED ISSUE #1621: [Bug]: two slash directives do not update in test panel
### What happened?

visit this challenge: https://typehero.dev/challenge/day-6

observe as you change code the types do not update in the test panel. you have to refresh to see the updated types

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aquibbaig**
This PR refreshes inlay hints on every code change by the user.

## Description

After every code edit by the user,
- dispose the current hint provider and register a new one in its place (debounced by 1s)
- The new provider automatically fetches new hints according to the new code and renders them on the editor.

## Related Issue

Closes #1621 

## Context

Again, this PR fixes #1621 which describes the issue of hints not updating after code changes. 

But wait a minute! This feature already works out of the box. Notice that when you change the Type on current production site and scroll on the "tests" editor -- the hints for the type will be updated as per the code change! You can test this on https://typehero.dev/challenge/day-6 by updating `type FilterChildrenBy = {};` and scrolling on "tests" editor)

## Motivation

- I noticed the fact `monaco.languages.registerInlayHintsProvider()` creates a new registration for all the "active" editors and listens for changes by default and updates hints accordingly. You can see that `createTwoslashInlayProvider` is called for both the editors of the split-screen.
- However, as code is changing, the "tests" editor does not update by itself (unless scrolled or edited) since it is readonly. We needed a method to programmatically trigger the updating of hints.
- As a first step, I moved the registration to `onChange` of the code-editor; but it created a new provider with every keystroke of a change and there could be multiple hints seen on the screen, which was pretty weird. 

e.g:
multiple providers

 
- So, I have disposed the existing instance and I am creating a new one in its place on code change.
- Additionally, to avoid potential conflicts, especially during rapid code edits I have added a `1s` debounce to refresh inlay hints on code change.

## How Has This Been Tested?

I have tested this feature manually across the following challenges and it fixes the issue as expected.
- https://typehero.dev/challenge/day-6
- https://typehero.dev/challenge/day-19
- https://typehero.dev/challenge/day-7

Note: Another fix could have been to manually update the hints after every code change using the editor instance but I could not find a reliable method to do so; therefore had to defer to re-registering the hints provider.

### CODE REVIEW

**Comment by bautistaaa** [comment]
ohh i didn't realize scrolling would update! that changes everything

**Comment by aquibbaig** [comment]
> ohh i didn't realize scrolling would update! that changes everything

yea, it's pretty weird. 

I still feel its worth refreshing hints on code change.

**Comment by bautistaaa** [comment]
> > ohh i didn't realize scrolling would update! that changes everything
> 
> 
> 
> yea, it's pretty weird. 
> 
> 
> 
> I still feel its worth refreshing hints on code change.

did you get it working 👀👀

**Comment by aquibbaig** [comment]
> did you get it working 👀👀

I did, yes!

**Review by bautistaaa — APPROVED** [review]
works for me!

thanks so much

**Pull request merged**
