### PR TITLE
Issue675: add all difficulty rows to explore page

### PR DESCRIPTION
**Pull request by WillGarman**
Add the `BEGINNER` and `EXTREME` challenges to /explore

## Description

I added 2 new `ExploreSection` components to the `/explore` page. 
- Beginner
- Extreme

I also changed the colors of the headings and buttons of Beginner and Extreme on the page since they did not match with the cards like the other sections.

Also, I changed the title for "Easy" cards to '"Hey, maybe I like TypeScript"' - this could of course be changed

## Related Issue

https://github.com/typehero/typehero/issues/675
## Motivation and Context

This will allow users who first land on the page to recognize that there are more difficulties than just 
- EASY
- MEDIUM
- HARD

The missing difficulties are hard to find unless you change the direct URL or they show up in new/most popular.

It is a simple fix that will increase user awareness

Open Issue: https://github.com/typehero/typehero/issues/675
## How Has This Been Tested?

The links work to the individual pages, everything loads onto `/explore`
## Screenshots/Video (if applicable):
Picture of new "Beginner" row
image

Picture of new "Extreme" row
image

### CODE REVIEW

**Review by bautistaaa — COMMENTED** [review]
i dont like that copy but i dont have a better solution. can you ask chatgpt lol

**Comment by WillGarman** [comment]
Yea I wasn't sure either will update them soon and commit

**Comment by WillGarman** [comment]
@bautistaaa we could go with something more simple like:
```
Beginner - "Great for Starters"
Easy - "Great for Learners"
Medium - "Great for Enthusiasts"
Hard - "Great for Experts"
Extreme - "Great for Masters"
```

or chatgpt really seems to like pushing these themed ones like:
```
Beginner - "Embarking on Adventure"
Easy - "Getting the Hang of It"
Medium - "Rising to the Challenge"
Hard - "Pushing the Limits"
Extreme - "Tackling the Titans"
```

there are tons, I personally like the more themed ones but I could understand the reason for using simpler headings. I also think what I come up with won't be perfect in the long run but it's an easy change if they want to change in the future. 

I will add some simple headings for now. Although I also don't know if I like them all starting with "Great for ..."

**Review by bautistaaa — APPROVED** [review]
ill tweak some later

**Comment by bautistaaa** [comment]
> hey @bautistaaa anything else you want on this before mege?

should be good to go

**Pull request merged**
