### PR TITLE
1369 mdwiltfong a11y reporting

### PR DESCRIPTION
**Pull request by mdwiltfong**
## Description

This PR will enable better reporting in regards to A11y Errors within playwright's html report. It will also provide an explanation on who to to view/handle these errors in `LOCAL.md`.

## Related Issue

Closes #

### CODE REVIEW

**Comment by mdwiltfong** [comment]
Okay, so I added a logger that gets called if there are any violations found. It prints to the CLI, but it also adds an attachment to the playwright HTML report. As you can tell from `a11yLogger.ts` it prints the following information in the following format:

```
function A11yLogger(violations: typeof axe.AxeResults.violations): void {
  violations.forEach((violation) => {
    console.log('--------------------------------------------------');
    console.log('Description: ', violation.description);
    console.log('Impact: ', violation.impact);
    console.log('Help: ', violation.help);
    console.log('Help URL: ', violation.helpUrl);
    console.log('Failure Summary: \n', violation.nodes[0]?.failureSummary);
    console.log('HTML: \n', violation.nodes[0]?.html);
    console.log('--------------------------------------------------');
  });
}
```

What do you think @bautistaaa ?

**Comment by mdwiltfong** [comment]
> Okay, so I added a logger that gets called if there are any violations found. It prints to the CLI, but it also adds an attachment to the playwright HTML report. As you can tell from `a11yLogger.ts` it prints the following information in the following format:
> 
> 
> 
> ```
> 
> function A11yLogger(violations: typeof axe.AxeResults.violations): void {
> 
>   violations.forEach((violation) => {
> 
>     console.log('--------------------------------------------------');
> 
>     console.log('Description: ', violation.description);
> 
>     console.log('Impact: ', violation.impact);
> 
>     console.log('Help: ', violation.help);
> 
>     console.log('Help URL: ', violation.helpUrl);
> 
>     console.log('Failure Summary: \n', violation.nodes[0]?.failureSummary);
> 
>     console.log('HTML: \n', violation.nodes[0]?.html);
> 
>     console.log('--------------------------------------------------');
> 
>   });
> 
> }
> 
> ```
> 
> 
> 
> What do you think @bautistaaa ?

I reached out to the open source team at Playwright, and they suggested a different route. Basically this custom logger needs to throw an error in order to enrich the HTML report.

**Comment by bautistaaa** [comment]
oh i just now saw the comment about what the team said. do you have a path forward here?

**Comment by mdwiltfong** [comment]
@bautistaaa ,

I have a solution but I need to test it. I'm getting some errors suddenly when running the test suite. Pretty sure they have nothing to do with my changes, but i'm trouble shooting it. Any chance you've encountered this ? 

Screenshot 2024-01-06 at 9 49 17 AM

**Comment by mdwiltfong** [comment]
Okay the problem went away! Those are the best problems. 

Looks like the tests are green. Here is a screen shot of the error peeps will see when they have a a11y error
Screenshot 2024-01-06 at 9 03 59 PM

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
