### PR TITLE
feat: add rewards+badges section under "About" aot

### PR DESCRIPTION
**Pull request by ayrock-dev**
## Description
lmk any copy feedback or thoughts on the colors

## Screenshots/Video (if applicable):

Click "About" on the AoT landing.

|Mobile|Desktop|
|---|---|
|Screenshot 2023-11-29 at 2 53 31 PM|Screenshot 2023-11-29 at 2 55 40 PM|

Then, see the `Rewards` section in the `About` pane.

|Mobile|Desktop|
|---|---|
|imageimageimage|imageimage|

### CODE REVIEW

**Comment by odicho** [comment]
The red color on the text seems a bit off. Can you try only highlighting the numbers or just bold the numbers?

**Comment by bautistaaa** [comment]
> The red color on the text seems a bit off. Can you try only highlighting the numbers or just bold the numbers?

yeah maybe just bolding or something works here

**Comment by ayrock-dev** [comment]
totally. done! gimme a min to update screenshots on PR

**Comment by odicho** [comment]
Small nit: I think the intro paragraph can be uplifted a little, perhaps a bit of a cheerful tone / Christmas vibes?

Example: "Earn and collect your Advent of TypeScript badges on your journey! Once earned, these badges will proudly display as achievements on your public profile. 🏆 Happy coding! ☃️"

**Comment by odicho** [comment]
Thanks for this, it looks awesome!! 🚀

**Comment by ayrock-dev** [comment]
Totally! Done. Went with-
> Earn and collect Advent of TypeScript badges on your journey! Once earned, these badges will be proudly displayed as achievements on your public profile. Happy coding! ☃️

**Review by odicho — APPROVED** [review]

**Pull request merged**
