### PR TITLE
feat: integrate ata

### PR DESCRIPTION
**Pull request by bautistaaa**
## Description
We want to be able to import 3rd party types in our challenges.

- [x] fetch types on change
- [x] fetch types on load
- [x] fetch types for test model
- [x] fetch types for user model
- [x] types successfully load in monaco
- [x] debounce the event for fetching types

### Sources
https://github.com/microsoft/TypeScript-Website/tree/9150ed65461c7ff0b3ec1b2085a30d26843fe3ec/packages/ata

## Related Issue

Closes https://github.com/typehero/typehero/issues/329

### CODE REVIEW

**Comment by QuiiBz** [comment]
Got it ~working but with a flood of errors in the console due to diagnostics:

Screenshot 2023-10-18 at 08 47 03

Screenshot 2023-10-18 at 08 47 14

**Comment by QuiiBz** [comment]
Ok it works now, there is still a 404 when loading this `/min/vs/basic-languages/javascript/javascript.js` file but everything seems to work fine (the first error is #889) 

Screenshot 2023-10-18 at 09 03 47

**Comment by bautistaaa** [comment]
CleanShot 2023-10-19 at 12 00 35@2x

im trying different scenarios with imports on and off on initial load and with `export` as well although i dont think i should be testing that atm

cc @QuiiBz

**Comment by QuiiBz** [comment]
Closing in favor of #916

**Pull request closed without merging**
