### PR TITLE
fix(profile): add remove button to url field

### LINKED ISSUE #724: [Feature]: The Add url field does not have any remove button
### Description

If the user accidentally clicks on add url he does not have any options to remove the field 
Screenshot 2023-09-27 at 11 23 05 AM

### Explanation

_No response_

### PR DESCRIPTION
**Pull request by aakash19here**
## Description
Removes the last index in the url field array

Closes #724 

## Screenshots/Video (if applicable):
Screenshot 2023-09-27 at 11 27 03 AM

### CODE REVIEW

**Comment by aakash19here** [comment]
We can do this too , tell me your opinions @bautistaaa 

Screenshot 2023-09-27 at 11 18 00 AM

**Comment by bautistaaa** [comment]
we should reinstate the old UI for urls and bio markdown editor which is in `settings/_components/index.tsx`

**Comment by aakash19here** [comment]
> we should reinstate the old UI for urls and bio markdown editor which is in `settings/_components/index.tsx`

Can I do it ?

**Comment by bautistaaa** [comment]
> > we should reinstate the old UI for urls and bio markdown editor which is in `settings/_components/index.tsx`
> 
> Can I do it ?

yes. please dont make issues and work on them immediately without running them by us first unless its obvious bugs on existing things

**Pull request closed without merging**
