### PR TITLE
[Bug]: Challenge OG image does not render correctly on twitter

### PR DESCRIPTION
**Pull request by aadamw**
Fixes dimensions of the challenge twitter-card

## Description
Adjust twitter-card OG image

## Related Issue
Closes https://github.com/typehero/typehero/issues/1060

## How Has This Been Tested?
Needs to be deployed to branch in order to test in twitter

## Screenshots/Video (if applicable):
Screenshot 2023-11-06 at 19 14 10

### CODE REVIEW

**Comment by bautistaaa** [comment]
@PickleNik any ideas on how to not make this look so doodoo now that the height is fixed >.<

**Comment by aadamw** [comment]
> @PickleNik any ideas on how to not make this look so doodoo now that the height is fixed >.<

Could you set min-height to the element and center it inside this container? WDYT>

**Comment by bautistaaa** [comment]
@aadamw ill give you creative freedom here on what you think would look best. def can constrain the inner container

**Comment by aadamw** [comment]
Screenshot 2023-11-06 at 19 46 13

**Comment by bautistaaa** [comment]
> Set min-h to 350px. I think It looks better than the one stretched Screenshot 2023-11-06 at 19 46 13

i likey

**Comment by bautistaaa** [comment]
lets merge and test i suppose yeah?

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
