### PR TITLE
better aot title

### PR DESCRIPTION
**Pull request by typesafegh**
## Related Issue

Closes #

### CODE REVIEW

**Comment by bautistaaa** [comment]
you ain’t even gonna post screenshots? 😂

**Comment by bautistaaa** [comment]
couple comments

- i dont think we need the sled animation (its cute though!)
- around sm - md res the header loses text-center. can you add text center to the sub header as well(existing i think)
- can we keep the gradient on mobile?

**Review by bautistaaa — APPROVED** [review]

**Comment by bautistaaa** [comment]
> couple comments
> 
> * i dont think we need the sled animation (its cute though!)
> * around sm - md res the header loses text-center. can you add text center to the sub header as well(existing i think)
> * can we keep the gradient on mobile?

sorry did them myself cause im about to make the page live

**Comment by typesafegh** [comment]
wanted to go to sleep 💀, thanks for doing the tweaks lol

**Pull request merged**
