### PR TITLE
feat: switch panel placement in a challenge

### LINKED ISSUE #1596: [Feature]: Ability to switch panel placement in a challenge (code on the left, instructions on the right)
### Description

a toggle to swap left panel with the right panel here
Screenshot 2024-10-20 at 1 10 11 AM

### Explanation

_No response_

### PR DESCRIPTION
**Pull request by nafisreza**
## Description

- Lets you switch panels in challenge to left/right and so forth
- Resizable on x axis and -x axis based on the orientation
- Hidden on mobile/tab as they have only a single column

### Future improvements:
- storing complete layout in local storage for better ux

## Related Issue

Closes #1596 

## Screenshots/Video (if applicable):
https://github.com/user-attachments/assets/abf856e3-cfde-407a-b262-9f5bbe36ddfd

### CODE REVIEW

**Comment by bautistaaa** [comment]
can you run `pnpm checks:fix`

**Comment by nafisreza** [comment]
@bautistaaa can you check now

**Comment by bautistaaa** [comment]
almost works. you cant collapse the panel when its on the right side. there should be some useEffect logic you need to reverse I think

CleanShot 2024-11-08 at 06 45 42

**Comment by nafisreza** [comment]
thanks @bautistaaa . Overlooked it. Fixed now.

https://github.com/user-attachments/assets/e42aaf07-7db1-415f-8fe7-c43b246c33ca

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
