### PR TITLE
Make the sitemap.xml use the database for good SEO

### PR DESCRIPTION
**Pull request by Hacksore**
good seo, yes yes yes

This will add all the challanges to the sitemap.xml

note: I am not doing caching so if it could be abused methinks

### CODE REVIEW

**Comment by Hacksore** [comment]
@bautistaaa should i use cache here?

**Comment by bautistaaa** [comment]
> @bautistaaa should i use cache here?

what cache, react cache? that wouldn’t do anything here. of you just mean cache headers or something

**Comment by Hacksore** [comment]
@bautistaaa i mean I don't know how to do cache headers here since this is some vercel/next abstraction.

tldr; do we need/want to cut down on db calls?

**Comment by bautistaaa** [comment]
probably since this is mainly static. idk much about this sitemap abstraction can we just generate it statically?

**Comment by bautistaaa** [comment]
https://vercel.com/guides/how-do-i-generate-a-sitemap-for-my-nextjs-app-on-vercel

**Comment by bautistaaa** [comment]
oh lame thats pages but anyways. we can just have a build script to generate this

**Comment by Hacksore** [comment]
also @invakid404 pointed out the static nature of the preview env.

https://typehero-git-feat-seo-moar-better-trash-company.vercel.app/sitemap.xml

**Review by bautistaaa — APPROVED** [review]

**Review by bautistaaa — APPROVED** [review]

**Pull request merged**
