### PR TITLE
fix: remove `z-index` from header

### PR DESCRIPTION
**Pull request by invakid404**
## Description

This PR removes the `z-index` from the header, which is the cause of elements in the header clipping
through tooltips that show over it.

## Related Issue

N/A

## Motivation and Context

This was an issue on the challenge page, as the tooltips of the buttons that are at the top of the
code editor show up over the header.

## How Has This Been Tested?

I've confirmed that all the links and buttons in the header appears to work correctly without a
`z-index`, so it should be fine.

## Screenshots/Video (if applicable):

Before the change:

image

After the change:

image

### CODE REVIEW

**Comment by invakid404** [comment]
Unfortunately, this is broken on the landing page for some reason. I'll investigate.

**Comment by invakid404** [comment]
The issue is that the hero section has a negative margin and overlaps with the header (which is probably why the z-index was useful in the first place). Nevertheless, I managed to fix it without z-index by disabling pointer events on the parent container (the one that overlaps) and re-enabling them for all children, which appears to work just fine.

**Comment by bautistaaa** [comment]
this disabled being able to click on anything in the nav on the homepage. Its probably because pointer event none on the hero component overlaps header me thinks

**Comment by invakid404** [comment]
@bautistaaa did you redeploy the preview/test this locally? The pointer-events-none is supposed to fix that.

**Comment by bautistaaa** [comment]
> @bautistaaa did you redeploy the preview/test this locally? The pointer-events-none is supposed to fix that.

thought I did. ill redeploy now

**Comment by invakid404** [comment]
@bautistaaa looks like it was still broken on mobile, which I somehow missed, but _now_ it should work lol

**Comment by bautistaaa** [comment]
this appears to work. fire in the hole

**Comment by bautistaaa** [comment]
looks like its broken on 404 page >.<

**Pull request merged**
