### PR TITLE
Feature/cache optimizations

### LINKED ISSUE #312: [performance] leverage react cache like we do for challenge pages

### PR DESCRIPTION
**Pull request by falcon-head**
## Description
Add cache for performance improvements
## Related Issue
Closes #312

### CODE REVIEW

**Comment by falcon-head** [comment]
@bautistaaa Feedback, please!

**Comment by bautistaaa** [comment]
I think we're missing some. Some off the top of my head the solutions/submissions route

**Comment by falcon-head** [comment]
@bautistaaa Can you review the PR, please?
- I have implemented caching wherever I thought it was necessary
- I'm unsure if we need caching `getUserData`?
- I do not have access to the admin routes, so can you test the cache functions there?

**Review by bautistaaa — APPROVED** [review]
should be okay. we can always follow up if we have any issues

**Pull request merged**
