### PR TITLE
feat:added primary blue color to resizer

### LINKED ISSUE #826: [Feature]: Add primary color on drag/hover of editor split
### Description

similar to VSCode can we make the little grabber turn the primary blue color when hover/dragging?

https://github.com/typehero/typehero/assets/996134/e7a7cf37-0c31-4648-a48a-49c90e4723d9

### Explanation

_No response_

### PR DESCRIPTION
**Pull request by shlok-2003**
## Description
- In `_component/component_layout.tsx`, below are the changes in tailwindcss of resizer component
    - removed `bg-neutral` and instead added `bg-primary`, for the `group-active` and `group-hover` cases.
    - works correctly for dark as well as for light mode

## Related Issue
Closes #826 

## How Has This Been Tested?
As mentioned in the **CONTRIBUTING.MD**, I run the `pnpm dev` & `pnpm test:e2e` commands.

## Screenshots/Video (if applicable):

https://github.com/typehero/typehero/assets/103599796/e66f1408-f047-41b3-867e-b5898d1b7204

### CODE REVIEW

**Comment by bautistaaa** [comment]
can you add same behavior to the test panel

**Comment by Hacksore** [comment]
> can you add same behavior to the test panel

i forgor about that, good call

**Comment by shlok-2003** [comment]
Hey @bautistaaa, can you specify exactly where I have to make the changes, as I cant find the test panel

**Comment by shlok-2003** [comment]
Hey @bautistaaa, I have made changes in the test panel, you can check them

**Review by Hacksore — APPROVED** [review]

**Pull request merged**
